### ISSUE TITLE
SytaxError

### ISSUE THREAD

**Issue by tuliosil** [LaskasP/TripAdvisor-Python-Scraper-Restaurants-2021#1]
Hi, my name is Tulio. I'm from Brazil. Nice to meet you. First of all, thank you very much for this script. 
I'm facing a problem with an invalid syntax running from your instructions in terminal: 

File "scraper.py", line 7
    < ! DOCTYPE html >
    ^
SyntaxError: invalid syntax

Do you know what it can be? 
Best
Tulio

**Comment by LaskasP** [comment]
Hey tuliosil,

It is a strange error because the script has nothing to do with html (except from scraping it).
Can you please attach your input?

Petros
