### ISSUE TITLE
Reviews in other languages

### ISSUE THREAD

**Issue by bartek810** [LaskasP/TripAdvisor-Python-Scraper-Restaurants-2021#2]
Hey your script only extracts english reviews. Is there a way to extract also the other ones?

**Comment by LaskasP** [comment]
Yeah, it is possible by making selenium driver to click on the All languages option on the tripAdvisor's review page. 
![Capture](https://user-images.githubusercontent.com/25673651/118849740-b2f85d00-b8d8-11eb-8020-68852d94967d.PNG)

Probably it's easy but I don't have enough time these days sorry, but i would implement it for sure when I am free. :)
